// Curated list of popular airports for the From/To city picker. Each renders as
// "City (CODE)" so selecting fills the field and cityCode() can parse the code.
export const AIRPORTS = [
  // India
  { code: 'DEL', city: 'Delhi', country: 'India' },
  { code: 'BOM', city: 'Mumbai', country: 'India' },
  { code: 'BLR', city: 'Bengaluru', country: 'India' },
  { code: 'MAA', city: 'Chennai', country: 'India' },
  { code: 'HYD', city: 'Hyderabad', country: 'India' },
  { code: 'CCU', city: 'Kolkata', country: 'India' },
  { code: 'GOI', city: 'Goa (Dabolim)', country: 'India' },
  { code: 'GOX', city: 'Goa (Mopa)', country: 'India' },
  { code: 'COK', city: 'Kochi', country: 'India' },
  { code: 'AMD', city: 'Ahmedabad', country: 'India' },
  { code: 'PNQ', city: 'Pune', country: 'India' },
  { code: 'JAI', city: 'Jaipur', country: 'India' },
  { code: 'LKO', city: 'Lucknow', country: 'India' },
  { code: 'IXC', city: 'Chandigarh', country: 'India' },
  { code: 'ATQ', city: 'Amritsar', country: 'India' },
  { code: 'IXZ', city: 'Port Blair', country: 'India' },
  { code: 'TRV', city: 'Thiruvananthapuram', country: 'India' },
  { code: 'IXB', city: 'Bagdogra', country: 'India' },
  { code: 'SXR', city: 'Srinagar', country: 'India' },
  { code: 'GAU', city: 'Guwahati', country: 'India' },
  { code: 'NAG', city: 'Nagpur', country: 'India' },
  { code: 'BBI', city: 'Bhubaneswar', country: 'India' },
  { code: 'PAT', city: 'Patna', country: 'India' },
  { code: 'VNS', city: 'Varanasi', country: 'India' },
  { code: 'UDR', city: 'Udaipur', country: 'India' },
  // Asia
  { code: 'BKK', city: 'Bangkok (Suvarnabhumi)', country: 'Thailand' },
  { code: 'DMK', city: 'Bangkok (Don Mueang)', country: 'Thailand' },
  { code: 'HKT', city: 'Phuket', country: 'Thailand' },
  { code: 'CNX', city: 'Chiang Mai', country: 'Thailand' },
  { code: 'USM', city: 'Koh Samui', country: 'Thailand' },
  { code: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'SIN', city: 'Singapore', country: 'Singapore' },
  { code: 'DPS', city: 'Bali (Denpasar)', country: 'Indonesia' },
  { code: 'CGK', city: 'Jakarta', country: 'Indonesia' },
  { code: 'HAN', city: 'Hanoi', country: 'Vietnam' },
  { code: 'SGN', city: 'Ho Chi Minh City', country: 'Vietnam' },
  { code: 'DAD', city: 'Da Nang', country: 'Vietnam' },
  { code: 'REP', city: 'Siem Reap', country: 'Cambodia' },
  { code: 'HKG', city: 'Hong Kong', country: 'Hong Kong' },
  { code: 'NRT', city: 'Tokyo (Narita)', country: 'Japan' },
  { code: 'HND', city: 'Tokyo (Haneda)', country: 'Japan' },
  { code: 'ICN', city: 'Seoul (Incheon)', country: 'South Korea' },
  { code: 'MLE', city: 'Malé', country: 'Maldives' },
  { code: 'CMB', city: 'Colombo', country: 'Sri Lanka' },
  { code: 'KTM', city: 'Kathmandu', country: 'Nepal' },
  { code: 'DXB', city: 'Dubai', country: 'UAE' },
  { code: 'AUH', city: 'Abu Dhabi', country: 'UAE' },
  { code: 'DOH', city: 'Doha', country: 'Qatar' },
  { code: 'RUH', city: 'Riyadh', country: 'Saudi Arabia' },
  { code: 'JED', city: 'Jeddah', country: 'Saudi Arabia' },
  { code: 'MCT', city: 'Muscat', country: 'Oman' },
  { code: 'KWI', city: 'Kuwait City', country: 'Kuwait' },
  // Europe
  { code: 'LHR', city: 'London (Heathrow)', country: 'UK' },
  { code: 'LGW', city: 'London (Gatwick)', country: 'UK' },
  { code: 'CDG', city: 'Paris (CDG)', country: 'France' },
  { code: 'AMS', city: 'Amsterdam', country: 'Netherlands' },
  { code: 'FRA', city: 'Frankfurt', country: 'Germany' },
  { code: 'MUC', city: 'Munich', country: 'Germany' },
  { code: 'ZRH', city: 'Zurich', country: 'Switzerland' },
  { code: 'IST', city: 'Istanbul', country: 'Türkiye' },
  { code: 'FCO', city: 'Rome', country: 'Italy' },
  { code: 'BCN', city: 'Barcelona', country: 'Spain' },
  // Americas & Oceania
  { code: 'JFK', city: 'New York (JFK)', country: 'USA' },
  { code: 'EWR', city: 'New York (Newark)', country: 'USA' },
  { code: 'SFO', city: 'San Francisco', country: 'USA' },
  { code: 'LAX', city: 'Los Angeles', country: 'USA' },
  { code: 'ORD', city: 'Chicago', country: 'USA' },
  { code: 'YYZ', city: 'Toronto', country: 'Canada' },
  { code: 'SYD', city: 'Sydney', country: 'Australia' },
  { code: 'MEL', city: 'Melbourne', country: 'Australia' },
]

// "City (CODE)" labels for a datalist.
export const CITY_OPTIONS = AIRPORTS.map((a) => `${a.city} (${a.code})`)
