import { chromium } from 'playwright'
const errs=[]
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage({ viewport: { width: 1400, height: 950 } })
page.setDefaultTimeout(6000)
page.on('pageerror',e=>errs.push(e.message))
await page.goto('file:///home/claude/oyo-tours-portal.html')
await page.waitForTimeout(600)
await page.getByText(/admin/i).first().click().catch(()=>{})
await page.waitForTimeout(500)
const s=page.getByRole('button',{name:/sign in|log in|continue|enter/i}).first(); if(await s.count()) await s.click().catch(()=>{})
await page.waitForTimeout(700)
await page.getByText(/packages/i).first().click().catch(()=>{})
await page.waitForTimeout(700)
await page.getByRole('button',{name:/bulk upload/i}).first().click().catch(()=>{})
await page.waitForTimeout(400)
await page.locator('input[type=file]').first().setInputFiles('/tmp/master.xlsx').catch(()=>{})
await page.waitForTimeout(700)
console.log('Preview pills present:', await page.getByText(/1 package/i).count())
const importBtn = page.getByRole('button',{name:/import 1 package/i}).first()
console.log('Import btn:', await importBtn.count())
await importBtn.click().catch(()=>{})
await page.waitForTimeout(700)
console.log('Created toast:', await page.getByText(/Created 1 package/i).count())
// close and search for the new package
await page.getByRole('button',{name:/close/i}).first().click().catch(()=>{})
await page.waitForTimeout(400)
await page.getByPlaceholder('Search').fill('Test Bulk').catch(()=>{})
await page.waitForTimeout(400)
console.log('New package visible:', await page.getByText(/Testville/i).count())
console.log('ERRORS:', errs.length?errs:'none')
await browser.close()
