import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } })
await page.goto('file:///home/claude/oyo-tours-portal.html')
await page.waitForTimeout(600)
await page.getByText(/admin/i).first().click().catch(()=>{})
await page.waitForTimeout(500)
const s = page.getByRole('button', { name: /sign in|log in|continue|enter/i }).first()
if (await s.count()) await s.click().catch(()=>{})
await page.waitForTimeout(600)
await page.getByText(/packages/i).first().click().catch(()=>{})
await page.waitForTimeout(600)
await page.locator('a[href^="/packages/"]').first().click().catch(()=>{})
await page.waitForTimeout(600)
await page.getByRole('button', { name: 'Departures', exact: true }).first().click().catch(()=>{})
await page.waitForTimeout(400)
const tbl = page.locator('table').first()
await tbl.scrollIntoViewIfNeeded()
await page.waitForTimeout(300)
await tbl.screenshot({ path: '/home/claude/tableonly.png' })
await browser.close()
